# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

kramdown:
  input: GFM
  hard_wrap: false

# Permalinks
permalink:        ':title'

# Setup
title:            kye-fr
url:              http://kye-fr.github.io
baseurl:          /

author:
  name:           'Kyle Hickey'

paginate:         5